controller:
  service:
    annotations:
      service.beta.kubernetes.io/upcloud-load-balancer-config: |
                {
                  "frontends": [
                    {
                      "name": "https",
                      "mode": "tcp",
                      "port": 443,
                      "default_backend": "https",
                      "networks": [
                        {
                          "name": "public-IPv4",
                          "type": "public"
                        },
                        {
                          "name": "private-IPv4"
                        }
                      ],
                      "tls_configs": [
                        {
                          "name": "phnx-infra-dev-cert",
                          "certificate_bundle_uuid": "0a60fc75-2e82-4bc9-b0e8-f51c1c245cee"
                        }
                      ],
                      "properties": {
                        "http2_enabled": true
                      }
                    },
                    {
                      "name": "grpc",
                      "mode": "tcp",
                      "port": 50051,
                      "default_backend": "https",
                      "networks": [
                        {
                          "name": "public-IPv4",
                          "type": "public"
                        },
                        {
                          "name": "private-IPv4"
                        }
                      ],
                      "tls_configs": [
                        {
                          "name": "phnx-infra-dev-cert",
                          "certificate_bundle_uuid": "0a60fc75-2e82-4bc9-b0e8-f51c1c245cee"
                        }
                      ],
                      "properties": {
                        "http2_enabled": true
                      }
                    }
                  ],
                  "backends": [
                    {
                      "name": "https",
                      "properties": {
                        "outbound_proxy_protocol": "v2",
                        "http2_enabled": true,
                        "tls_enabled": true
                      }
                    }
                  ]
                }
  config:
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"
    use-proxy-protocol: "true"
    real-ip-header: "proxy_protocol"
